import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "lib/generated/**",
    // Custom ignores:
    "components/ui/**", // UI components are auto-generated by a design tool.
    "worker-configuration.d.ts", // Worker configuration file.
    ".wrangler/**", // Wrangler configuration files.
    
  ]),
]);

export default eslintConfig;
